// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: service/commands/echo_swerve_sample.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SwerveSample } from "../../entity/swerve_sample";

export interface EchoSwerveSampleRequest {
  sample: SwerveSample | null;
}

export interface EchoSwerveSampleResponse {
  sample: SwerveSample | null;
}

function createBaseEchoSwerveSampleRequest(): EchoSwerveSampleRequest {
  return { sample: null };
}

export const EchoSwerveSampleRequest: MessageFns<EchoSwerveSampleRequest> = {
  encode(message: EchoSwerveSampleRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sample !== undefined && message.sample !== null) {
      SwerveSample.encode(message.sample, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EchoSwerveSampleRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEchoSwerveSampleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sample = SwerveSample.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EchoSwerveSampleRequest {
    return { sample: isSet(object.sample) ? SwerveSample.fromJSON(object.sample) : null };
  },

  toJSON(message: EchoSwerveSampleRequest): unknown {
    const obj: any = {};
    if (message.sample !== undefined && message.sample !== null) {
      obj.sample = SwerveSample.toJSON(message.sample);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EchoSwerveSampleRequest>, I>>(base?: I): EchoSwerveSampleRequest {
    return EchoSwerveSampleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EchoSwerveSampleRequest>, I>>(object: I): EchoSwerveSampleRequest {
    const message = createBaseEchoSwerveSampleRequest();
    message.sample = (object.sample !== undefined && object.sample !== null)
      ? SwerveSample.fromPartial(object.sample)
      : null;
    return message;
  },
};

function createBaseEchoSwerveSampleResponse(): EchoSwerveSampleResponse {
  return { sample: null };
}

export const EchoSwerveSampleResponse: MessageFns<EchoSwerveSampleResponse> = {
  encode(message: EchoSwerveSampleResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sample !== undefined && message.sample !== null) {
      SwerveSample.encode(message.sample, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EchoSwerveSampleResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEchoSwerveSampleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sample = SwerveSample.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EchoSwerveSampleResponse {
    return { sample: isSet(object.sample) ? SwerveSample.fromJSON(object.sample) : null };
  },

  toJSON(message: EchoSwerveSampleResponse): unknown {
    const obj: any = {};
    if (message.sample !== undefined && message.sample !== null) {
      obj.sample = SwerveSample.toJSON(message.sample);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EchoSwerveSampleResponse>, I>>(base?: I): EchoSwerveSampleResponse {
    return EchoSwerveSampleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EchoSwerveSampleResponse>, I>>(object: I): EchoSwerveSampleResponse {
    const message = createBaseEchoSwerveSampleResponse();
    message.sample = (object.sample !== undefined && object.sample !== null)
      ? SwerveSample.fromPartial(object.sample)
      : null;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
