// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: service/commands/generate.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { TrajectoryFile } from "../../entity/trajectory_file";

export interface GenerateRequest {
  trajectory: TrajectoryFile | null;
}

export interface GenerateResponse {
  trajectory: TrajectoryFile | null;
}

function createBaseGenerateRequest(): GenerateRequest {
  return { trajectory: null };
}

export const GenerateRequest: MessageFns<GenerateRequest> = {
  encode(message: GenerateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trajectory !== undefined && message.trajectory !== null) {
      TrajectoryFile.encode(message.trajectory, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trajectory = TrajectoryFile.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateRequest {
    return { trajectory: isSet(object.trajectory) ? TrajectoryFile.fromJSON(object.trajectory) : null };
  },

  toJSON(message: GenerateRequest): unknown {
    const obj: any = {};
    if (message.trajectory !== undefined && message.trajectory !== null) {
      obj.trajectory = TrajectoryFile.toJSON(message.trajectory);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateRequest>, I>>(base?: I): GenerateRequest {
    return GenerateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateRequest>, I>>(object: I): GenerateRequest {
    const message = createBaseGenerateRequest();
    message.trajectory = (object.trajectory !== undefined && object.trajectory !== null)
      ? TrajectoryFile.fromPartial(object.trajectory)
      : null;
    return message;
  },
};

function createBaseGenerateResponse(): GenerateResponse {
  return { trajectory: null };
}

export const GenerateResponse: MessageFns<GenerateResponse> = {
  encode(message: GenerateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trajectory !== undefined && message.trajectory !== null) {
      TrajectoryFile.encode(message.trajectory, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trajectory = TrajectoryFile.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateResponse {
    return { trajectory: isSet(object.trajectory) ? TrajectoryFile.fromJSON(object.trajectory) : null };
  },

  toJSON(message: GenerateResponse): unknown {
    const obj: any = {};
    if (message.trajectory !== undefined && message.trajectory !== null) {
      obj.trajectory = TrajectoryFile.toJSON(message.trajectory);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateResponse>, I>>(base?: I): GenerateResponse {
    return GenerateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateResponse>, I>>(object: I): GenerateResponse {
    const message = createBaseGenerateResponse();
    message.trajectory = (object.trajectory !== undefined && object.trajectory !== null)
      ? TrajectoryFile.fromPartial(object.trajectory)
      : null;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
