// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: service/service.proto

/* eslint-disable */
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { Empty } from "../google/protobuf/empty";
import { EchoSwerveSampleRequest, EchoSwerveSampleResponse } from "./commands/echo_swerve_sample";
import { GenerateRequest, GenerateResponse } from "./commands/generate";
import { GetDefaultTrajectoryResponse } from "./commands/get_default_trajectory";

export interface ChoreoService {
  EchoSwerveSample(
    request: DeepPartial<EchoSwerveSampleRequest>,
    metadata?: grpc.Metadata,
  ): Promise<EchoSwerveSampleResponse>;
  Generate(request: DeepPartial<GenerateRequest>, metadata?: grpc.Metadata): Promise<GenerateResponse>;
  GetDefaultTrajectory(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<GetDefaultTrajectoryResponse>;
}

export class ChoreoServiceClientImpl implements ChoreoService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.EchoSwerveSample = this.EchoSwerveSample.bind(this);
    this.Generate = this.Generate.bind(this);
    this.GetDefaultTrajectory = this.GetDefaultTrajectory.bind(this);
  }

  EchoSwerveSample(
    request: DeepPartial<EchoSwerveSampleRequest>,
    metadata?: grpc.Metadata,
  ): Promise<EchoSwerveSampleResponse> {
    return this.rpc.unary(ChoreoServiceEchoSwerveSampleDesc, EchoSwerveSampleRequest.fromPartial(request), metadata);
  }

  Generate(request: DeepPartial<GenerateRequest>, metadata?: grpc.Metadata): Promise<GenerateResponse> {
    return this.rpc.unary(ChoreoServiceGenerateDesc, GenerateRequest.fromPartial(request), metadata);
  }

  GetDefaultTrajectory(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<GetDefaultTrajectoryResponse> {
    return this.rpc.unary(ChoreoServiceGetDefaultTrajectoryDesc, Empty.fromPartial(request), metadata);
  }
}

export const ChoreoServiceDesc = { serviceName: "service.ChoreoService" };

export const ChoreoServiceEchoSwerveSampleDesc: UnaryMethodDefinitionish = {
  methodName: "EchoSwerveSample",
  service: ChoreoServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return EchoSwerveSampleRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = EchoSwerveSampleResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const ChoreoServiceGenerateDesc: UnaryMethodDefinitionish = {
  methodName: "Generate",
  service: ChoreoServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return GenerateRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = GenerateResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const ChoreoServiceGetDefaultTrajectoryDesc: UnaryMethodDefinitionish = {
  methodName: "GetDefaultTrajectory",
  service: ChoreoServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = GetDefaultTrajectoryResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;

    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;

      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}
