// @generated
// This file is @generated by prost-build.
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprModule {
    #[prost(message, optional, tag = "1")]
    pub x: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "2")]
    pub y: ::core::option::Option<super::super::Expr>,
}
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprBumper {
    #[prost(message, optional, tag = "1")]
    pub front: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "2")]
    pub left: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "3")]
    pub right: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "4")]
    pub back: ::core::option::Option<super::super::Expr>,
}
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprRobotConfig {
    #[prost(message, optional, tag = "1")]
    pub mass: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "2")]
    pub inertia: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "3")]
    pub gearing: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "4")]
    pub radius: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "5")]
    pub vmax: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "6")]
    pub tmax: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "7")]
    pub cof: ::core::option::Option<super::super::Expr>,
    #[prost(message, optional, tag = "8")]
    pub differential_track_width: ::core::option::Option<super::super::Expr>,
    /// Expr bumper_front = 9;
    /// Expr bumper_left = 10;
    /// Expr bumper_back = 11;
    /// Expr bumper_right = 12;
    /// Expr fl_x = 13;
    /// Expr fl_y = 14;
    /// Expr fr_x = 15;
    /// Expr fl_
    #[prost(message, optional, tag = "9")]
    pub bumper: ::core::option::Option<ExprBumper>,
    #[prost(message, optional, tag = "10")]
    pub front_left: ::core::option::Option<ExprModule>,
    #[prost(message, optional, tag = "11")]
    pub front_right: ::core::option::Option<ExprModule>,
    #[prost(message, optional, tag = "12")]
    pub back_left: ::core::option::Option<ExprModule>,
    #[prost(message, optional, tag = "13")]
    pub back_right: ::core::option::Option<ExprModule>,
}
// @@protoc_insertion_point(module)
