// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/constraint/max_acceleration/expr.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Expr } from "../../expression";

export interface ExprMaxAcceleration {
  max: Expr | undefined;
}

function createBaseExprMaxAcceleration(): ExprMaxAcceleration {
  return { max: undefined };
}

export const ExprMaxAcceleration: MessageFns<ExprMaxAcceleration> = {
  encode(message: ExprMaxAcceleration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.max !== undefined) {
      Expr.encode(message.max, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprMaxAcceleration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprMaxAcceleration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.max = Expr.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprMaxAcceleration {
    return { max: isSet(object.max) ? Expr.fromJSON(object.max) : undefined };
  },

  toJSON(message: ExprMaxAcceleration): unknown {
    const obj: any = {};
    if (message.max !== undefined) {
      obj.max = Expr.toJSON(message.max);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprMaxAcceleration>, I>>(base?: I): ExprMaxAcceleration {
    return ExprMaxAcceleration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprMaxAcceleration>, I>>(object: I): ExprMaxAcceleration {
    const message = createBaseExprMaxAcceleration();
    message.max = (object.max !== undefined && object.max !== null) ? Expr.fromPartial(object.max) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
