// @generated
// This file is @generated by prost-build.
#[derive(valid_proc::Valid)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WaypointIdFirst {
}
#[derive(valid_proc::Valid)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WaypointIdLast {
}
#[derive(valid_proc::Valid)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WaypointIdx {
    #[prost(uint64, tag = "1")]
    pub idx: u64,
}
#[derive(valid_proc::Valid)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WaypointId {
    #[prost(oneof = "waypoint_id::Id", tags = "1, 2, 3")]
    pub id: ::core::option::Option<waypoint_id::Id>,
}
/// Nested message and enum types in `WaypointID`.
pub mod waypoint_id {
    #[derive(valid_proc::Valid)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Id {
        #[prost(message, tag = "1")]
        First(super::WaypointIdFirst),
        #[prost(message, tag = "2")]
        Last(super::WaypointIdLast),
        #[prost(message, tag = "3")]
        Idx(super::WaypointIdx),
    }
}
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprParameters {
    #[prost(message, optional, tag = "1")]
    pub target_dt: ::core::option::Option<super::Expr>,
    #[prost(message, repeated, tag = "2")]
    pub waypoints: ::prost::alloc::vec::Vec<waypoint::ExprWaypoint>,
    #[prost(message, repeated, tag = "3")]
    pub constraints: ::prost::alloc::vec::Vec<constraint::ExprConstraint>,
}
// @@protoc_insertion_point(module)
