// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/waypoint/double.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface DoubleWaypoint {
  x: number;
  y: number;
  heading: number;
  intervals: number;
  split: boolean;
  fixTranslation: boolean;
  fixHeading: boolean;
  overrideIntervals: boolean;
}

function createBaseDoubleWaypoint(): DoubleWaypoint {
  return {
    x: 0,
    y: 0,
    heading: 0,
    intervals: 0,
    split: false,
    fixTranslation: false,
    fixHeading: false,
    overrideIntervals: false,
  };
}

export const DoubleWaypoint: MessageFns<DoubleWaypoint> = {
  encode(message: DoubleWaypoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(9).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(17).double(message.y);
    }
    if (message.heading !== 0) {
      writer.uint32(25).double(message.heading);
    }
    if (message.intervals !== 0) {
      writer.uint32(32).uint64(message.intervals);
    }
    if (message.split !== false) {
      writer.uint32(40).bool(message.split);
    }
    if (message.fixTranslation !== false) {
      writer.uint32(48).bool(message.fixTranslation);
    }
    if (message.fixHeading !== false) {
      writer.uint32(56).bool(message.fixHeading);
    }
    if (message.overrideIntervals !== false) {
      writer.uint32(64).bool(message.overrideIntervals);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DoubleWaypoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDoubleWaypoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.x = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.y = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.heading = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.intervals = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.split = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.fixTranslation = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.fixHeading = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.overrideIntervals = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DoubleWaypoint {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      heading: isSet(object.heading) ? globalThis.Number(object.heading) : 0,
      intervals: isSet(object.intervals) ? globalThis.Number(object.intervals) : 0,
      split: isSet(object.split) ? globalThis.Boolean(object.split) : false,
      fixTranslation: isSet(object.fixTranslation)
        ? globalThis.Boolean(object.fixTranslation)
        : isSet(object.fix_translation)
        ? globalThis.Boolean(object.fix_translation)
        : false,
      fixHeading: isSet(object.fixHeading)
        ? globalThis.Boolean(object.fixHeading)
        : isSet(object.fix_heading)
        ? globalThis.Boolean(object.fix_heading)
        : false,
      overrideIntervals: isSet(object.overrideIntervals)
        ? globalThis.Boolean(object.overrideIntervals)
        : isSet(object.override_intervals)
        ? globalThis.Boolean(object.override_intervals)
        : false,
    };
  },

  toJSON(message: DoubleWaypoint): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.heading !== 0) {
      obj.heading = message.heading;
    }
    if (message.intervals !== 0) {
      obj.intervals = Math.round(message.intervals);
    }
    if (message.split !== false) {
      obj.split = message.split;
    }
    if (message.fixTranslation !== false) {
      obj.fixTranslation = message.fixTranslation;
    }
    if (message.fixHeading !== false) {
      obj.fixHeading = message.fixHeading;
    }
    if (message.overrideIntervals !== false) {
      obj.overrideIntervals = message.overrideIntervals;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DoubleWaypoint>, I>>(base?: I): DoubleWaypoint {
    return DoubleWaypoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DoubleWaypoint>, I>>(object: I): DoubleWaypoint {
    const message = createBaseDoubleWaypoint();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.heading = object.heading ?? 0;
    message.intervals = object.intervals ?? 0;
    message.split = object.split ?? false;
    message.fixTranslation = object.fixTranslation ?? false;
    message.fixHeading = object.fixHeading ?? false;
    message.overrideIntervals = object.overrideIntervals ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
