// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/waypoint/expr.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Expr } from "../../expression";

export interface ExprWaypoint {
  x: Expr | undefined;
  y: Expr | undefined;
  heading: Expr | undefined;
  intervals: number;
  split: boolean;
  fixTranslation: boolean;
  fixHeading: boolean;
  overrideIntervals: boolean;
}

function createBaseExprWaypoint(): ExprWaypoint {
  return {
    x: undefined,
    y: undefined,
    heading: undefined,
    intervals: 0,
    split: false,
    fixTranslation: false,
    fixHeading: false,
    overrideIntervals: false,
  };
}

export const ExprWaypoint: MessageFns<ExprWaypoint> = {
  encode(message: ExprWaypoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== undefined) {
      Expr.encode(message.x, writer.uint32(10).fork()).join();
    }
    if (message.y !== undefined) {
      Expr.encode(message.y, writer.uint32(18).fork()).join();
    }
    if (message.heading !== undefined) {
      Expr.encode(message.heading, writer.uint32(26).fork()).join();
    }
    if (message.intervals !== 0) {
      writer.uint32(32).uint64(message.intervals);
    }
    if (message.split !== false) {
      writer.uint32(40).bool(message.split);
    }
    if (message.fixTranslation !== false) {
      writer.uint32(48).bool(message.fixTranslation);
    }
    if (message.fixHeading !== false) {
      writer.uint32(56).bool(message.fixHeading);
    }
    if (message.overrideIntervals !== false) {
      writer.uint32(64).bool(message.overrideIntervals);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprWaypoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprWaypoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.x = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.y = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.heading = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.intervals = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.split = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.fixTranslation = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.fixHeading = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.overrideIntervals = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprWaypoint {
    return {
      x: isSet(object.x) ? Expr.fromJSON(object.x) : undefined,
      y: isSet(object.y) ? Expr.fromJSON(object.y) : undefined,
      heading: isSet(object.heading) ? Expr.fromJSON(object.heading) : undefined,
      intervals: isSet(object.intervals) ? globalThis.Number(object.intervals) : 0,
      split: isSet(object.split) ? globalThis.Boolean(object.split) : false,
      fixTranslation: isSet(object.fixTranslation)
        ? globalThis.Boolean(object.fixTranslation)
        : isSet(object.fix_translation)
        ? globalThis.Boolean(object.fix_translation)
        : false,
      fixHeading: isSet(object.fixHeading)
        ? globalThis.Boolean(object.fixHeading)
        : isSet(object.fix_heading)
        ? globalThis.Boolean(object.fix_heading)
        : false,
      overrideIntervals: isSet(object.overrideIntervals)
        ? globalThis.Boolean(object.overrideIntervals)
        : isSet(object.override_intervals)
        ? globalThis.Boolean(object.override_intervals)
        : false,
    };
  },

  toJSON(message: ExprWaypoint): unknown {
    const obj: any = {};
    if (message.x !== undefined) {
      obj.x = Expr.toJSON(message.x);
    }
    if (message.y !== undefined) {
      obj.y = Expr.toJSON(message.y);
    }
    if (message.heading !== undefined) {
      obj.heading = Expr.toJSON(message.heading);
    }
    if (message.intervals !== 0) {
      obj.intervals = Math.round(message.intervals);
    }
    if (message.split !== false) {
      obj.split = message.split;
    }
    if (message.fixTranslation !== false) {
      obj.fixTranslation = message.fixTranslation;
    }
    if (message.fixHeading !== false) {
      obj.fixHeading = message.fixHeading;
    }
    if (message.overrideIntervals !== false) {
      obj.overrideIntervals = message.overrideIntervals;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprWaypoint>, I>>(base?: I): ExprWaypoint {
    return ExprWaypoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprWaypoint>, I>>(object: I): ExprWaypoint {
    const message = createBaseExprWaypoint();
    message.x = (object.x !== undefined && object.x !== null) ? Expr.fromPartial(object.x) : undefined;
    message.y = (object.y !== undefined && object.y !== null) ? Expr.fromPartial(object.y) : undefined;
    message.heading = (object.heading !== undefined && object.heading !== null)
      ? Expr.fromPartial(object.heading)
      : undefined;
    message.intervals = object.intervals ?? 0;
    message.split = object.split ?? false;
    message.fixTranslation = object.fixTranslation ?? false;
    message.fixHeading = object.fixHeading ?? false;
    message.overrideIntervals = object.overrideIntervals ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
