// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DoubleMaxVelocity {
    #[prost(double, tag = "1")]
    pub max: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprMaxVelocity {
    #[prost(message, optional, tag = "1")]
    pub max: ::core::option::Option<super::super::Expr>,
}
include!("entity.parameters.constraint.max_velocity.serde.rs");
// @@protoc_insertion_point(module)