// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/differential_sample.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface DifferentialSample {
  t: number;
  x: number;
  y: number;
  heading: number;
  vl: number;
  vr: number;
  omega: number;
  al: number;
  ar: number;
  alpha: number;
  fl: number;
  fr: number;
}

function createBaseDifferentialSample(): DifferentialSample {
  return { t: 0, x: 0, y: 0, heading: 0, vl: 0, vr: 0, omega: 0, al: 0, ar: 0, alpha: 0, fl: 0, fr: 0 };
}

export const DifferentialSample: MessageFns<DifferentialSample> = {
  encode(message: DifferentialSample, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.t !== 0) {
      writer.uint32(9).double(message.t);
    }
    if (message.x !== 0) {
      writer.uint32(17).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(25).double(message.y);
    }
    if (message.heading !== 0) {
      writer.uint32(33).double(message.heading);
    }
    if (message.vl !== 0) {
      writer.uint32(41).double(message.vl);
    }
    if (message.vr !== 0) {
      writer.uint32(49).double(message.vr);
    }
    if (message.omega !== 0) {
      writer.uint32(57).double(message.omega);
    }
    if (message.al !== 0) {
      writer.uint32(65).double(message.al);
    }
    if (message.ar !== 0) {
      writer.uint32(73).double(message.ar);
    }
    if (message.alpha !== 0) {
      writer.uint32(81).double(message.alpha);
    }
    if (message.fl !== 0) {
      writer.uint32(89).double(message.fl);
    }
    if (message.fr !== 0) {
      writer.uint32(97).double(message.fr);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DifferentialSample {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDifferentialSample();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.t = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.x = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.y = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.heading = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.vl = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.vr = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.omega = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.al = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.ar = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 81) {
            break;
          }

          message.alpha = reader.double();
          continue;
        }
        case 11: {
          if (tag !== 89) {
            break;
          }

          message.fl = reader.double();
          continue;
        }
        case 12: {
          if (tag !== 97) {
            break;
          }

          message.fr = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DifferentialSample {
    return {
      t: isSet(object.t) ? globalThis.Number(object.t) : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      heading: isSet(object.heading) ? globalThis.Number(object.heading) : 0,
      vl: isSet(object.vl) ? globalThis.Number(object.vl) : 0,
      vr: isSet(object.vr) ? globalThis.Number(object.vr) : 0,
      omega: isSet(object.omega) ? globalThis.Number(object.omega) : 0,
      al: isSet(object.al) ? globalThis.Number(object.al) : 0,
      ar: isSet(object.ar) ? globalThis.Number(object.ar) : 0,
      alpha: isSet(object.alpha) ? globalThis.Number(object.alpha) : 0,
      fl: isSet(object.fl) ? globalThis.Number(object.fl) : 0,
      fr: isSet(object.fr) ? globalThis.Number(object.fr) : 0,
    };
  },

  toJSON(message: DifferentialSample): unknown {
    const obj: any = {};
    if (message.t !== 0) {
      obj.t = message.t;
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.heading !== 0) {
      obj.heading = message.heading;
    }
    if (message.vl !== 0) {
      obj.vl = message.vl;
    }
    if (message.vr !== 0) {
      obj.vr = message.vr;
    }
    if (message.omega !== 0) {
      obj.omega = message.omega;
    }
    if (message.al !== 0) {
      obj.al = message.al;
    }
    if (message.ar !== 0) {
      obj.ar = message.ar;
    }
    if (message.alpha !== 0) {
      obj.alpha = message.alpha;
    }
    if (message.fl !== 0) {
      obj.fl = message.fl;
    }
    if (message.fr !== 0) {
      obj.fr = message.fr;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DifferentialSample>, I>>(base?: I): DifferentialSample {
    return DifferentialSample.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DifferentialSample>, I>>(object: I): DifferentialSample {
    const message = createBaseDifferentialSample();
    message.t = object.t ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.heading = object.heading ?? 0;
    message.vl = object.vl ?? 0;
    message.vr = object.vr ?? 0;
    message.omega = object.omega ?? 0;
    message.al = object.al ?? 0;
    message.ar = object.ar ?? 0;
    message.alpha = object.alpha ?? 0;
    message.fl = object.fl ?? 0;
    message.fr = object.fr ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
