// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/drive_type.proto

/* eslint-disable */

export enum DriveType {
  DRIVETYPE_SWERVE = 0,
  DRIVETYPE_DIFFERENTIAL = 1,
  DRIVETYPE_MECANUM = 2,
  UNRECOGNIZED = -1,
}

export function driveTypeFromJSON(object: any): DriveType {
  switch (object) {
    case 0:
    case "DRIVETYPE_SWERVE":
      return DriveType.DRIVETYPE_SWERVE;
    case 1:
    case "DRIVETYPE_DIFFERENTIAL":
      return DriveType.DRIVETYPE_DIFFERENTIAL;
    case 2:
    case "DRIVETYPE_MECANUM":
      return DriveType.DRIVETYPE_MECANUM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DriveType.UNRECOGNIZED;
  }
}

export function driveTypeToJSON(object: DriveType): string {
  switch (object) {
    case DriveType.DRIVETYPE_SWERVE:
      return "DRIVETYPE_SWERVE";
    case DriveType.DRIVETYPE_DIFFERENTIAL:
      return "DRIVETYPE_DIFFERENTIAL";
    case DriveType.DRIVETYPE_MECANUM:
      return "DRIVETYPE_MECANUM";
    case DriveType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
