// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/drive_type.proto

/* eslint-disable */

export enum DriveType {
  DRIVE_TYPE_SWERVE = 0,
  DRIVE_TYPE_DIFFERENTIAL = 1,
  DRIVE_TYPE_MECANUM = 2,
  UNRECOGNIZED = -1,
}

export function driveTypeFromJSON(object: any): DriveType {
  switch (object) {
    case 0:
    case "DRIVE_TYPE_SWERVE":
      return DriveType.DRIVE_TYPE_SWERVE;
    case 1:
    case "DRIVE_TYPE_DIFFERENTIAL":
      return DriveType.DRIVE_TYPE_DIFFERENTIAL;
    case 2:
    case "DRIVE_TYPE_MECANUM":
      return DriveType.DRIVE_TYPE_MECANUM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DriveType.UNRECOGNIZED;
  }
}

export function driveTypeToJSON(object: DriveType): string {
  switch (object) {
    case DriveType.DRIVE_TYPE_SWERVE:
      return "DRIVE_TYPE_SWERVE";
    case DriveType.DRIVE_TYPE_DIFFERENTIAL:
      return "DRIVE_TYPE_DIFFERENTIAL";
    case DriveType.DRIVE_TYPE_MECANUM:
      return "DRIVE_TYPE_MECANUM";
    case DriveType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
