// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/project_file.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { DriveType, driveTypeFromJSON, driveTypeToJSON } from "./drive_type";
import { ExprRobotConfig } from "./parameters/robotconfig/expr";

export interface ProjectFile {
  name: string;
  config: ExprRobotConfig | null;
  driveType: DriveType;
}

function createBaseProjectFile(): ProjectFile {
  return { name: "", config: null, driveType: 0 };
}

export const ProjectFile: MessageFns<ProjectFile> = {
  encode(message: ProjectFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.config !== undefined && message.config !== null) {
      ExprRobotConfig.encode(message.config, writer.uint32(18).fork()).join();
    }
    if (message.driveType !== 0) {
      writer.uint32(24).int32(message.driveType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProjectFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProjectFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.config = ExprRobotConfig.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.driveType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProjectFile {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      config: isSet(object.config) ? ExprRobotConfig.fromJSON(object.config) : null,
      driveType: isSet(object.driveType)
        ? driveTypeFromJSON(object.driveType)
        : isSet(object.drive_type)
        ? driveTypeFromJSON(object.drive_type)
        : 0,
    };
  },

  toJSON(message: ProjectFile): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.config !== undefined && message.config !== null) {
      obj.config = ExprRobotConfig.toJSON(message.config);
    }
    if (message.driveType !== 0) {
      obj.driveType = driveTypeToJSON(message.driveType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProjectFile>, I>>(base?: I): ProjectFile {
    return ProjectFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProjectFile>, I>>(object: I): ProjectFile {
    const message = createBaseProjectFile();
    message.name = object.name ?? "";
    message.config = (object.config !== undefined && object.config !== null)
      ? ExprRobotConfig.fromPartial(object.config)
      : null;
    message.driveType = object.driveType ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
