// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/swerve_sample.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface ForceVector {
  x: number;
  y: number;
}

export interface SwerveSample {
  t: number;
  x: number;
  y: number;
  heading: number;
  vx: number;
  vy: number;
  omega: number;
  ax: number;
  ay: number;
  alpha: number;
  fl: ForceVector | undefined;
  fr: ForceVector | undefined;
  bl: ForceVector | undefined;
  br: ForceVector | undefined;
}

function createBaseForceVector(): ForceVector {
  return { x: 0, y: 0 };
}

export const ForceVector: MessageFns<ForceVector> = {
  encode(message: ForceVector, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(9).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(17).double(message.y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ForceVector {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseForceVector();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.x = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.y = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ForceVector {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: ForceVector): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ForceVector>, I>>(base?: I): ForceVector {
    return ForceVector.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ForceVector>, I>>(object: I): ForceVector {
    const message = createBaseForceVector();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

function createBaseSwerveSample(): SwerveSample {
  return {
    t: 0,
    x: 0,
    y: 0,
    heading: 0,
    vx: 0,
    vy: 0,
    omega: 0,
    ax: 0,
    ay: 0,
    alpha: 0,
    fl: undefined,
    fr: undefined,
    bl: undefined,
    br: undefined,
  };
}

export const SwerveSample: MessageFns<SwerveSample> = {
  encode(message: SwerveSample, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.t !== 0) {
      writer.uint32(9).double(message.t);
    }
    if (message.x !== 0) {
      writer.uint32(17).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(25).double(message.y);
    }
    if (message.heading !== 0) {
      writer.uint32(33).double(message.heading);
    }
    if (message.vx !== 0) {
      writer.uint32(41).double(message.vx);
    }
    if (message.vy !== 0) {
      writer.uint32(49).double(message.vy);
    }
    if (message.omega !== 0) {
      writer.uint32(57).double(message.omega);
    }
    if (message.ax !== 0) {
      writer.uint32(65).double(message.ax);
    }
    if (message.ay !== 0) {
      writer.uint32(73).double(message.ay);
    }
    if (message.alpha !== 0) {
      writer.uint32(81).double(message.alpha);
    }
    if (message.fl !== undefined) {
      ForceVector.encode(message.fl, writer.uint32(90).fork()).join();
    }
    if (message.fr !== undefined) {
      ForceVector.encode(message.fr, writer.uint32(98).fork()).join();
    }
    if (message.bl !== undefined) {
      ForceVector.encode(message.bl, writer.uint32(106).fork()).join();
    }
    if (message.br !== undefined) {
      ForceVector.encode(message.br, writer.uint32(114).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SwerveSample {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSwerveSample();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.t = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.x = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.y = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.heading = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.vx = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.vy = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.omega = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.ax = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.ay = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 81) {
            break;
          }

          message.alpha = reader.double();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.fl = ForceVector.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.fr = ForceVector.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.bl = ForceVector.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.br = ForceVector.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SwerveSample {
    return {
      t: isSet(object.t) ? globalThis.Number(object.t) : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      heading: isSet(object.heading) ? globalThis.Number(object.heading) : 0,
      vx: isSet(object.vx) ? globalThis.Number(object.vx) : 0,
      vy: isSet(object.vy) ? globalThis.Number(object.vy) : 0,
      omega: isSet(object.omega) ? globalThis.Number(object.omega) : 0,
      ax: isSet(object.ax) ? globalThis.Number(object.ax) : 0,
      ay: isSet(object.ay) ? globalThis.Number(object.ay) : 0,
      alpha: isSet(object.alpha) ? globalThis.Number(object.alpha) : 0,
      fl: isSet(object.fl) ? ForceVector.fromJSON(object.fl) : undefined,
      fr: isSet(object.fr) ? ForceVector.fromJSON(object.fr) : undefined,
      bl: isSet(object.bl) ? ForceVector.fromJSON(object.bl) : undefined,
      br: isSet(object.br) ? ForceVector.fromJSON(object.br) : undefined,
    };
  },

  toJSON(message: SwerveSample): unknown {
    const obj: any = {};
    if (message.t !== 0) {
      obj.t = message.t;
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.heading !== 0) {
      obj.heading = message.heading;
    }
    if (message.vx !== 0) {
      obj.vx = message.vx;
    }
    if (message.vy !== 0) {
      obj.vy = message.vy;
    }
    if (message.omega !== 0) {
      obj.omega = message.omega;
    }
    if (message.ax !== 0) {
      obj.ax = message.ax;
    }
    if (message.ay !== 0) {
      obj.ay = message.ay;
    }
    if (message.alpha !== 0) {
      obj.alpha = message.alpha;
    }
    if (message.fl !== undefined) {
      obj.fl = ForceVector.toJSON(message.fl);
    }
    if (message.fr !== undefined) {
      obj.fr = ForceVector.toJSON(message.fr);
    }
    if (message.bl !== undefined) {
      obj.bl = ForceVector.toJSON(message.bl);
    }
    if (message.br !== undefined) {
      obj.br = ForceVector.toJSON(message.br);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwerveSample>, I>>(base?: I): SwerveSample {
    return SwerveSample.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwerveSample>, I>>(object: I): SwerveSample {
    const message = createBaseSwerveSample();
    message.t = object.t ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.heading = object.heading ?? 0;
    message.vx = object.vx ?? 0;
    message.vy = object.vy ?? 0;
    message.omega = object.omega ?? 0;
    message.ax = object.ax ?? 0;
    message.ay = object.ay ?? 0;
    message.alpha = object.alpha ?? 0;
    message.fl = (object.fl !== undefined && object.fl !== null) ? ForceVector.fromPartial(object.fl) : undefined;
    message.fr = (object.fr !== undefined && object.fr !== null) ? ForceVector.fromPartial(object.fr) : undefined;
    message.bl = (object.bl !== undefined && object.bl !== null) ? ForceVector.fromPartial(object.bl) : undefined;
    message.br = (object.br !== undefined && object.br !== null) ? ForceVector.fromPartial(object.br) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
