// @generated
// This file is @generated by prost-build.
#[derive(valid_proc::Valid)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EchoSwerveSampleRequest {
    #[prost(message, optional, tag = "1")]
    pub sample: ::core::option::Option<super::super::entity::SwerveSample>,
}
#[derive(valid_proc::Valid)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EchoSwerveSampleResponse {
    #[prost(message, optional, tag = "1")]
    pub sample: ::core::option::Option<super::super::entity::SwerveSample>,
}
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenerateRequest {
    #[prost(message, optional, tag = "1")]
    pub trajectory: ::core::option::Option<super::super::entity::TrajectoryFile>,
}
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenerateResponse {
    #[prost(message, optional, tag = "1")]
    pub trajectory: ::core::option::Option<super::super::entity::TrajectoryFile>,
}
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDefaultTrajectoryResponse {
    #[prost(message, optional, tag = "1")]
    pub trajectory: ::core::option::Option<super::super::entity::TrajectoryFile>,
}
// @@protoc_insertion_point(module)
