// @generated
// This file is @generated by prost-build.
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprConstraint {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(message, optional, tag = "2")]
    pub from: ::core::option::Option<super::WaypointId>,
    #[prost(message, optional, tag = "3")]
    pub to: ::core::option::Option<super::WaypointId>,
    /// ExprMaxVelocity maxvelocity = 4;
    /// ExprMaxAcceleration max_acceleration = 5;
    #[prost(oneof = "expr_constraint::Data", tags = "4, 5")]
    pub data: ::core::option::Option<expr_constraint::Data>,
}
/// Nested message and enum types in `ExprConstraint`.
pub mod expr_constraint {
    /// ExprMaxVelocity maxvelocity = 4;
    /// ExprMaxAcceleration max_acceleration = 5;
    #[derive(valid_proc::Valid)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "4")]
        MaxVelocity(super::maxvelocity::ExprMaxVelocity),
        #[prost(message, tag = "5")]
        MaxAcceleration(super::max_acceleration::ExprMaxAcceleration),
    }
}
// @@protoc_insertion_point(module)
