// @generated
// This file is @generated by prost-build.
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprMaxAcceleration {
    #[prost(message, optional, tag = "1")]
    pub max: ::core::option::Option<super::super::super::Expr>,
}
// @@protoc_insertion_point(module)
