// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown

/* eslint-disable */

export * as entity from "./index.entity";
export * as service from "./index.service";
