// @generated
// This file is @generated by prost-build.
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprMaxVelocity {
    #[prost(message, optional, tag = "1")]
    pub max: ::core::option::Option<super::super::super::Expr>,
}
#[derive(valid_proc::Valid)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestExpr {
    #[prost(string, tag = "1")]
    pub test: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
