// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/robotconfig/double.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface DoubleModule {
  x: number;
  y: number;
}

export interface DoubleBumper {
  front: number;
  left: number;
  right: number;
  back: number;
}

export interface DoubleRobotConfig {
  mass: number;
  inertia: number;
  gearing: number;
  radius: number;
  vmax: number;
  tmax: number;
  cof: number;
  differentialTrackWidth: number;
  /**
   * double bumper_front = 9;
   * double bumper_left = 10;
   * double bumper_back = 11;
   * double bumper_right = 12;
   * double fl_x = 13;
   * double fl_y = 14;
   * double fr_x = 15;
   * double fl_
   */
  bumper: DoubleBumper | undefined;
  frontLeft: DoubleModule | undefined;
  frontRight: DoubleModule | undefined;
  backLeft: DoubleModule | undefined;
  backRight: DoubleModule | undefined;
}

function createBaseDoubleModule(): DoubleModule {
  return { x: 0, y: 0 };
}

export const DoubleModule: MessageFns<DoubleModule> = {
  encode(message: DoubleModule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(9).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(17).double(message.y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DoubleModule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDoubleModule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.x = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.y = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DoubleModule {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: DoubleModule): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DoubleModule>, I>>(base?: I): DoubleModule {
    return DoubleModule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DoubleModule>, I>>(object: I): DoubleModule {
    const message = createBaseDoubleModule();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

function createBaseDoubleBumper(): DoubleBumper {
  return { front: 0, left: 0, right: 0, back: 0 };
}

export const DoubleBumper: MessageFns<DoubleBumper> = {
  encode(message: DoubleBumper, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.front !== 0) {
      writer.uint32(9).double(message.front);
    }
    if (message.left !== 0) {
      writer.uint32(17).double(message.left);
    }
    if (message.right !== 0) {
      writer.uint32(25).double(message.right);
    }
    if (message.back !== 0) {
      writer.uint32(33).double(message.back);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DoubleBumper {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDoubleBumper();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.front = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.left = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.right = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.back = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DoubleBumper {
    return {
      front: isSet(object.front) ? globalThis.Number(object.front) : 0,
      left: isSet(object.left) ? globalThis.Number(object.left) : 0,
      right: isSet(object.right) ? globalThis.Number(object.right) : 0,
      back: isSet(object.back) ? globalThis.Number(object.back) : 0,
    };
  },

  toJSON(message: DoubleBumper): unknown {
    const obj: any = {};
    if (message.front !== 0) {
      obj.front = message.front;
    }
    if (message.left !== 0) {
      obj.left = message.left;
    }
    if (message.right !== 0) {
      obj.right = message.right;
    }
    if (message.back !== 0) {
      obj.back = message.back;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DoubleBumper>, I>>(base?: I): DoubleBumper {
    return DoubleBumper.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DoubleBumper>, I>>(object: I): DoubleBumper {
    const message = createBaseDoubleBumper();
    message.front = object.front ?? 0;
    message.left = object.left ?? 0;
    message.right = object.right ?? 0;
    message.back = object.back ?? 0;
    return message;
  },
};

function createBaseDoubleRobotConfig(): DoubleRobotConfig {
  return {
    mass: 0,
    inertia: 0,
    gearing: 0,
    radius: 0,
    vmax: 0,
    tmax: 0,
    cof: 0,
    differentialTrackWidth: 0,
    bumper: undefined,
    frontLeft: undefined,
    frontRight: undefined,
    backLeft: undefined,
    backRight: undefined,
  };
}

export const DoubleRobotConfig: MessageFns<DoubleRobotConfig> = {
  encode(message: DoubleRobotConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mass !== 0) {
      writer.uint32(9).double(message.mass);
    }
    if (message.inertia !== 0) {
      writer.uint32(17).double(message.inertia);
    }
    if (message.gearing !== 0) {
      writer.uint32(25).double(message.gearing);
    }
    if (message.radius !== 0) {
      writer.uint32(33).double(message.radius);
    }
    if (message.vmax !== 0) {
      writer.uint32(41).double(message.vmax);
    }
    if (message.tmax !== 0) {
      writer.uint32(49).double(message.tmax);
    }
    if (message.cof !== 0) {
      writer.uint32(57).double(message.cof);
    }
    if (message.differentialTrackWidth !== 0) {
      writer.uint32(65).double(message.differentialTrackWidth);
    }
    if (message.bumper !== undefined) {
      DoubleBumper.encode(message.bumper, writer.uint32(74).fork()).join();
    }
    if (message.frontLeft !== undefined) {
      DoubleModule.encode(message.frontLeft, writer.uint32(82).fork()).join();
    }
    if (message.frontRight !== undefined) {
      DoubleModule.encode(message.frontRight, writer.uint32(90).fork()).join();
    }
    if (message.backLeft !== undefined) {
      DoubleModule.encode(message.backLeft, writer.uint32(98).fork()).join();
    }
    if (message.backRight !== undefined) {
      DoubleModule.encode(message.backRight, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DoubleRobotConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDoubleRobotConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.mass = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.inertia = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.gearing = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.radius = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.vmax = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.tmax = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.cof = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.differentialTrackWidth = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.bumper = DoubleBumper.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.frontLeft = DoubleModule.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.frontRight = DoubleModule.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.backLeft = DoubleModule.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.backRight = DoubleModule.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DoubleRobotConfig {
    return {
      mass: isSet(object.mass) ? globalThis.Number(object.mass) : 0,
      inertia: isSet(object.inertia) ? globalThis.Number(object.inertia) : 0,
      gearing: isSet(object.gearing) ? globalThis.Number(object.gearing) : 0,
      radius: isSet(object.radius) ? globalThis.Number(object.radius) : 0,
      vmax: isSet(object.vmax) ? globalThis.Number(object.vmax) : 0,
      tmax: isSet(object.tmax) ? globalThis.Number(object.tmax) : 0,
      cof: isSet(object.cof) ? globalThis.Number(object.cof) : 0,
      differentialTrackWidth: isSet(object.differentialTrackWidth)
        ? globalThis.Number(object.differentialTrackWidth)
        : isSet(object.differential_track_width)
        ? globalThis.Number(object.differential_track_width)
        : 0,
      bumper: isSet(object.bumper) ? DoubleBumper.fromJSON(object.bumper) : undefined,
      frontLeft: isSet(object.frontLeft)
        ? DoubleModule.fromJSON(object.frontLeft)
        : isSet(object.front_left)
        ? DoubleModule.fromJSON(object.front_left)
        : undefined,
      frontRight: isSet(object.frontRight)
        ? DoubleModule.fromJSON(object.frontRight)
        : isSet(object.front_right)
        ? DoubleModule.fromJSON(object.front_right)
        : undefined,
      backLeft: isSet(object.backLeft)
        ? DoubleModule.fromJSON(object.backLeft)
        : isSet(object.back_left)
        ? DoubleModule.fromJSON(object.back_left)
        : undefined,
      backRight: isSet(object.backRight)
        ? DoubleModule.fromJSON(object.backRight)
        : isSet(object.back_right)
        ? DoubleModule.fromJSON(object.back_right)
        : undefined,
    };
  },

  toJSON(message: DoubleRobotConfig): unknown {
    const obj: any = {};
    if (message.mass !== 0) {
      obj.mass = message.mass;
    }
    if (message.inertia !== 0) {
      obj.inertia = message.inertia;
    }
    if (message.gearing !== 0) {
      obj.gearing = message.gearing;
    }
    if (message.radius !== 0) {
      obj.radius = message.radius;
    }
    if (message.vmax !== 0) {
      obj.vmax = message.vmax;
    }
    if (message.tmax !== 0) {
      obj.tmax = message.tmax;
    }
    if (message.cof !== 0) {
      obj.cof = message.cof;
    }
    if (message.differentialTrackWidth !== 0) {
      obj.differentialTrackWidth = message.differentialTrackWidth;
    }
    if (message.bumper !== undefined) {
      obj.bumper = DoubleBumper.toJSON(message.bumper);
    }
    if (message.frontLeft !== undefined) {
      obj.frontLeft = DoubleModule.toJSON(message.frontLeft);
    }
    if (message.frontRight !== undefined) {
      obj.frontRight = DoubleModule.toJSON(message.frontRight);
    }
    if (message.backLeft !== undefined) {
      obj.backLeft = DoubleModule.toJSON(message.backLeft);
    }
    if (message.backRight !== undefined) {
      obj.backRight = DoubleModule.toJSON(message.backRight);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DoubleRobotConfig>, I>>(base?: I): DoubleRobotConfig {
    return DoubleRobotConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DoubleRobotConfig>, I>>(object: I): DoubleRobotConfig {
    const message = createBaseDoubleRobotConfig();
    message.mass = object.mass ?? 0;
    message.inertia = object.inertia ?? 0;
    message.gearing = object.gearing ?? 0;
    message.radius = object.radius ?? 0;
    message.vmax = object.vmax ?? 0;
    message.tmax = object.tmax ?? 0;
    message.cof = object.cof ?? 0;
    message.differentialTrackWidth = object.differentialTrackWidth ?? 0;
    message.bumper = (object.bumper !== undefined && object.bumper !== null)
      ? DoubleBumper.fromPartial(object.bumper)
      : undefined;
    message.frontLeft = (object.frontLeft !== undefined && object.frontLeft !== null)
      ? DoubleModule.fromPartial(object.frontLeft)
      : undefined;
    message.frontRight = (object.frontRight !== undefined && object.frontRight !== null)
      ? DoubleModule.fromPartial(object.frontRight)
      : undefined;
    message.backLeft = (object.backLeft !== undefined && object.backLeft !== null)
      ? DoubleModule.fromPartial(object.backLeft)
      : undefined;
    message.backRight = (object.backRight !== undefined && object.backRight !== null)
      ? DoubleModule.fromPartial(object.backRight)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
