// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/robotconfig/expr.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Expr } from "../../expression";

export interface ExprModule {
  x: Expr | null;
  y: Expr | null;
}

export interface ExprBumper {
  front: Expr | null;
  left: Expr | null;
  right: Expr | null;
  back: Expr | null;
}

export interface ExprRobotConfig {
  mass: Expr | null;
  inertia: Expr | null;
  gearing: Expr | null;
  radius: Expr | null;
  vmax: Expr | null;
  tmax: Expr | null;
  cof: Expr | null;
  differentialTrackWidth:
    | Expr
    | null;
  /**
   * Expr bumper_front = 9;
   * Expr bumper_left = 10;
   * Expr bumper_back = 11;
   * Expr bumper_right = 12;
   * Expr fl_x = 13;
   * Expr fl_y = 14;
   * Expr fr_x = 15;
   * Expr fl_
   */
  bumper: ExprBumper | null;
  frontLeft: ExprModule | null;
  frontRight: ExprModule | null;
  backLeft: ExprModule | null;
  backRight: ExprModule | null;
}

function createBaseExprModule(): ExprModule {
  return { x: null, y: null };
}

export const ExprModule: MessageFns<ExprModule> = {
  encode(message: ExprModule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== undefined && message.x !== null) {
      Expr.encode(message.x, writer.uint32(10).fork()).join();
    }
    if (message.y !== undefined && message.y !== null) {
      Expr.encode(message.y, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprModule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprModule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.x = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.y = Expr.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprModule {
    return { x: isSet(object.x) ? Expr.fromJSON(object.x) : null, y: isSet(object.y) ? Expr.fromJSON(object.y) : null };
  },

  toJSON(message: ExprModule): unknown {
    const obj: any = {};
    if (message.x !== undefined && message.x !== null) {
      obj.x = Expr.toJSON(message.x);
    }
    if (message.y !== undefined && message.y !== null) {
      obj.y = Expr.toJSON(message.y);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprModule>, I>>(base?: I): ExprModule {
    return ExprModule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprModule>, I>>(object: I): ExprModule {
    const message = createBaseExprModule();
    message.x = (object.x !== undefined && object.x !== null) ? Expr.fromPartial(object.x) : null;
    message.y = (object.y !== undefined && object.y !== null) ? Expr.fromPartial(object.y) : null;
    return message;
  },
};

function createBaseExprBumper(): ExprBumper {
  return { front: null, left: null, right: null, back: null };
}

export const ExprBumper: MessageFns<ExprBumper> = {
  encode(message: ExprBumper, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.front !== undefined && message.front !== null) {
      Expr.encode(message.front, writer.uint32(10).fork()).join();
    }
    if (message.left !== undefined && message.left !== null) {
      Expr.encode(message.left, writer.uint32(18).fork()).join();
    }
    if (message.right !== undefined && message.right !== null) {
      Expr.encode(message.right, writer.uint32(26).fork()).join();
    }
    if (message.back !== undefined && message.back !== null) {
      Expr.encode(message.back, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprBumper {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprBumper();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.front = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.left = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.right = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.back = Expr.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprBumper {
    return {
      front: isSet(object.front) ? Expr.fromJSON(object.front) : null,
      left: isSet(object.left) ? Expr.fromJSON(object.left) : null,
      right: isSet(object.right) ? Expr.fromJSON(object.right) : null,
      back: isSet(object.back) ? Expr.fromJSON(object.back) : null,
    };
  },

  toJSON(message: ExprBumper): unknown {
    const obj: any = {};
    if (message.front !== undefined && message.front !== null) {
      obj.front = Expr.toJSON(message.front);
    }
    if (message.left !== undefined && message.left !== null) {
      obj.left = Expr.toJSON(message.left);
    }
    if (message.right !== undefined && message.right !== null) {
      obj.right = Expr.toJSON(message.right);
    }
    if (message.back !== undefined && message.back !== null) {
      obj.back = Expr.toJSON(message.back);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprBumper>, I>>(base?: I): ExprBumper {
    return ExprBumper.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprBumper>, I>>(object: I): ExprBumper {
    const message = createBaseExprBumper();
    message.front = (object.front !== undefined && object.front !== null) ? Expr.fromPartial(object.front) : null;
    message.left = (object.left !== undefined && object.left !== null) ? Expr.fromPartial(object.left) : null;
    message.right = (object.right !== undefined && object.right !== null) ? Expr.fromPartial(object.right) : null;
    message.back = (object.back !== undefined && object.back !== null) ? Expr.fromPartial(object.back) : null;
    return message;
  },
};

function createBaseExprRobotConfig(): ExprRobotConfig {
  return {
    mass: null,
    inertia: null,
    gearing: null,
    radius: null,
    vmax: null,
    tmax: null,
    cof: null,
    differentialTrackWidth: null,
    bumper: null,
    frontLeft: null,
    frontRight: null,
    backLeft: null,
    backRight: null,
  };
}

export const ExprRobotConfig: MessageFns<ExprRobotConfig> = {
  encode(message: ExprRobotConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mass !== undefined && message.mass !== null) {
      Expr.encode(message.mass, writer.uint32(10).fork()).join();
    }
    if (message.inertia !== undefined && message.inertia !== null) {
      Expr.encode(message.inertia, writer.uint32(18).fork()).join();
    }
    if (message.gearing !== undefined && message.gearing !== null) {
      Expr.encode(message.gearing, writer.uint32(26).fork()).join();
    }
    if (message.radius !== undefined && message.radius !== null) {
      Expr.encode(message.radius, writer.uint32(34).fork()).join();
    }
    if (message.vmax !== undefined && message.vmax !== null) {
      Expr.encode(message.vmax, writer.uint32(42).fork()).join();
    }
    if (message.tmax !== undefined && message.tmax !== null) {
      Expr.encode(message.tmax, writer.uint32(50).fork()).join();
    }
    if (message.cof !== undefined && message.cof !== null) {
      Expr.encode(message.cof, writer.uint32(58).fork()).join();
    }
    if (message.differentialTrackWidth !== undefined && message.differentialTrackWidth !== null) {
      Expr.encode(message.differentialTrackWidth, writer.uint32(66).fork()).join();
    }
    if (message.bumper !== undefined && message.bumper !== null) {
      ExprBumper.encode(message.bumper, writer.uint32(74).fork()).join();
    }
    if (message.frontLeft !== undefined && message.frontLeft !== null) {
      ExprModule.encode(message.frontLeft, writer.uint32(82).fork()).join();
    }
    if (message.frontRight !== undefined && message.frontRight !== null) {
      ExprModule.encode(message.frontRight, writer.uint32(90).fork()).join();
    }
    if (message.backLeft !== undefined && message.backLeft !== null) {
      ExprModule.encode(message.backLeft, writer.uint32(98).fork()).join();
    }
    if (message.backRight !== undefined && message.backRight !== null) {
      ExprModule.encode(message.backRight, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprRobotConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprRobotConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mass = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.inertia = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.gearing = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.radius = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.vmax = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.tmax = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.cof = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.differentialTrackWidth = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.bumper = ExprBumper.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.frontLeft = ExprModule.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.frontRight = ExprModule.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.backLeft = ExprModule.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.backRight = ExprModule.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprRobotConfig {
    return {
      mass: isSet(object.mass) ? Expr.fromJSON(object.mass) : null,
      inertia: isSet(object.inertia) ? Expr.fromJSON(object.inertia) : null,
      gearing: isSet(object.gearing) ? Expr.fromJSON(object.gearing) : null,
      radius: isSet(object.radius) ? Expr.fromJSON(object.radius) : null,
      vmax: isSet(object.vmax) ? Expr.fromJSON(object.vmax) : null,
      tmax: isSet(object.tmax) ? Expr.fromJSON(object.tmax) : null,
      cof: isSet(object.cof) ? Expr.fromJSON(object.cof) : null,
      differentialTrackWidth: isSet(object.differentialTrackWidth)
        ? Expr.fromJSON(object.differentialTrackWidth)
        : isSet(object.differential_track_width)
        ? Expr.fromJSON(object.differential_track_width)
        : null,
      bumper: isSet(object.bumper) ? ExprBumper.fromJSON(object.bumper) : null,
      frontLeft: isSet(object.frontLeft)
        ? ExprModule.fromJSON(object.frontLeft)
        : isSet(object.front_left)
        ? ExprModule.fromJSON(object.front_left)
        : null,
      frontRight: isSet(object.frontRight)
        ? ExprModule.fromJSON(object.frontRight)
        : isSet(object.front_right)
        ? ExprModule.fromJSON(object.front_right)
        : null,
      backLeft: isSet(object.backLeft)
        ? ExprModule.fromJSON(object.backLeft)
        : isSet(object.back_left)
        ? ExprModule.fromJSON(object.back_left)
        : null,
      backRight: isSet(object.backRight)
        ? ExprModule.fromJSON(object.backRight)
        : isSet(object.back_right)
        ? ExprModule.fromJSON(object.back_right)
        : null,
    };
  },

  toJSON(message: ExprRobotConfig): unknown {
    const obj: any = {};
    if (message.mass !== undefined && message.mass !== null) {
      obj.mass = Expr.toJSON(message.mass);
    }
    if (message.inertia !== undefined && message.inertia !== null) {
      obj.inertia = Expr.toJSON(message.inertia);
    }
    if (message.gearing !== undefined && message.gearing !== null) {
      obj.gearing = Expr.toJSON(message.gearing);
    }
    if (message.radius !== undefined && message.radius !== null) {
      obj.radius = Expr.toJSON(message.radius);
    }
    if (message.vmax !== undefined && message.vmax !== null) {
      obj.vmax = Expr.toJSON(message.vmax);
    }
    if (message.tmax !== undefined && message.tmax !== null) {
      obj.tmax = Expr.toJSON(message.tmax);
    }
    if (message.cof !== undefined && message.cof !== null) {
      obj.cof = Expr.toJSON(message.cof);
    }
    if (message.differentialTrackWidth !== undefined && message.differentialTrackWidth !== null) {
      obj.differentialTrackWidth = Expr.toJSON(message.differentialTrackWidth);
    }
    if (message.bumper !== undefined && message.bumper !== null) {
      obj.bumper = ExprBumper.toJSON(message.bumper);
    }
    if (message.frontLeft !== undefined && message.frontLeft !== null) {
      obj.frontLeft = ExprModule.toJSON(message.frontLeft);
    }
    if (message.frontRight !== undefined && message.frontRight !== null) {
      obj.frontRight = ExprModule.toJSON(message.frontRight);
    }
    if (message.backLeft !== undefined && message.backLeft !== null) {
      obj.backLeft = ExprModule.toJSON(message.backLeft);
    }
    if (message.backRight !== undefined && message.backRight !== null) {
      obj.backRight = ExprModule.toJSON(message.backRight);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprRobotConfig>, I>>(base?: I): ExprRobotConfig {
    return ExprRobotConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprRobotConfig>, I>>(object: I): ExprRobotConfig {
    const message = createBaseExprRobotConfig();
    message.mass = (object.mass !== undefined && object.mass !== null) ? Expr.fromPartial(object.mass) : null;
    message.inertia = (object.inertia !== undefined && object.inertia !== null)
      ? Expr.fromPartial(object.inertia)
      : null;
    message.gearing = (object.gearing !== undefined && object.gearing !== null)
      ? Expr.fromPartial(object.gearing)
      : null;
    message.radius = (object.radius !== undefined && object.radius !== null) ? Expr.fromPartial(object.radius) : null;
    message.vmax = (object.vmax !== undefined && object.vmax !== null) ? Expr.fromPartial(object.vmax) : null;
    message.tmax = (object.tmax !== undefined && object.tmax !== null) ? Expr.fromPartial(object.tmax) : null;
    message.cof = (object.cof !== undefined && object.cof !== null) ? Expr.fromPartial(object.cof) : null;
    message.differentialTrackWidth =
      (object.differentialTrackWidth !== undefined && object.differentialTrackWidth !== null)
        ? Expr.fromPartial(object.differentialTrackWidth)
        : null;
    message.bumper = (object.bumper !== undefined && object.bumper !== null)
      ? ExprBumper.fromPartial(object.bumper)
      : null;
    message.frontLeft = (object.frontLeft !== undefined && object.frontLeft !== null)
      ? ExprModule.fromPartial(object.frontLeft)
      : null;
    message.frontRight = (object.frontRight !== undefined && object.frontRight !== null)
      ? ExprModule.fromPartial(object.frontRight)
      : null;
    message.backLeft = (object.backLeft !== undefined && object.backLeft !== null)
      ? ExprModule.fromPartial(object.backLeft)
      : null;
    message.backRight = (object.backRight !== undefined && object.backRight !== null)
      ? ExprModule.fromPartial(object.backRight)
      : null;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
