// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/robotconfig/expr.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Expr } from "../expression";

export interface ExprModule {
  x: Expr | undefined;
  y: Expr | undefined;
}

export interface ExprBumper {
  front: Expr | undefined;
  left: Expr | undefined;
  right: Expr | undefined;
  back: Expr | undefined;
}

export interface ExprRobotConfig {
  mass: Expr | undefined;
  inertia: Expr | undefined;
  gearing: Expr | undefined;
  radius: Expr | undefined;
  vmax: Expr | undefined;
  tmax: Expr | undefined;
  cof: Expr | undefined;
  differentialTrackWidth:
    | Expr
    | undefined;
  /**
   * Expr bumper_front = 9;
   * Expr bumper_left = 10;
   * Expr bumper_back = 11;
   * Expr bumper_right = 12;
   * Expr fl_x = 13;
   * Expr fl_y = 14;
   * Expr fr_x = 15;
   * Expr fl_
   */
  bumper: ExprBumper | undefined;
  frontLeft: ExprModule | undefined;
  frontRight: ExprModule | undefined;
  backLeft: ExprModule | undefined;
  backRight: ExprModule | undefined;
}

function createBaseExprModule(): ExprModule {
  return { x: undefined, y: undefined };
}

export const ExprModule: MessageFns<ExprModule> = {
  encode(message: ExprModule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== undefined) {
      Expr.encode(message.x, writer.uint32(10).fork()).join();
    }
    if (message.y !== undefined) {
      Expr.encode(message.y, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprModule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprModule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.x = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.y = Expr.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprModule {
    return {
      x: isSet(object.x) ? Expr.fromJSON(object.x) : undefined,
      y: isSet(object.y) ? Expr.fromJSON(object.y) : undefined,
    };
  },

  toJSON(message: ExprModule): unknown {
    const obj: any = {};
    if (message.x !== undefined) {
      obj.x = Expr.toJSON(message.x);
    }
    if (message.y !== undefined) {
      obj.y = Expr.toJSON(message.y);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprModule>, I>>(base?: I): ExprModule {
    return ExprModule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprModule>, I>>(object: I): ExprModule {
    const message = createBaseExprModule();
    message.x = (object.x !== undefined && object.x !== null) ? Expr.fromPartial(object.x) : undefined;
    message.y = (object.y !== undefined && object.y !== null) ? Expr.fromPartial(object.y) : undefined;
    return message;
  },
};

function createBaseExprBumper(): ExprBumper {
  return { front: undefined, left: undefined, right: undefined, back: undefined };
}

export const ExprBumper: MessageFns<ExprBumper> = {
  encode(message: ExprBumper, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.front !== undefined) {
      Expr.encode(message.front, writer.uint32(10).fork()).join();
    }
    if (message.left !== undefined) {
      Expr.encode(message.left, writer.uint32(18).fork()).join();
    }
    if (message.right !== undefined) {
      Expr.encode(message.right, writer.uint32(26).fork()).join();
    }
    if (message.back !== undefined) {
      Expr.encode(message.back, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprBumper {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprBumper();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.front = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.left = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.right = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.back = Expr.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprBumper {
    return {
      front: isSet(object.front) ? Expr.fromJSON(object.front) : undefined,
      left: isSet(object.left) ? Expr.fromJSON(object.left) : undefined,
      right: isSet(object.right) ? Expr.fromJSON(object.right) : undefined,
      back: isSet(object.back) ? Expr.fromJSON(object.back) : undefined,
    };
  },

  toJSON(message: ExprBumper): unknown {
    const obj: any = {};
    if (message.front !== undefined) {
      obj.front = Expr.toJSON(message.front);
    }
    if (message.left !== undefined) {
      obj.left = Expr.toJSON(message.left);
    }
    if (message.right !== undefined) {
      obj.right = Expr.toJSON(message.right);
    }
    if (message.back !== undefined) {
      obj.back = Expr.toJSON(message.back);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprBumper>, I>>(base?: I): ExprBumper {
    return ExprBumper.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprBumper>, I>>(object: I): ExprBumper {
    const message = createBaseExprBumper();
    message.front = (object.front !== undefined && object.front !== null) ? Expr.fromPartial(object.front) : undefined;
    message.left = (object.left !== undefined && object.left !== null) ? Expr.fromPartial(object.left) : undefined;
    message.right = (object.right !== undefined && object.right !== null) ? Expr.fromPartial(object.right) : undefined;
    message.back = (object.back !== undefined && object.back !== null) ? Expr.fromPartial(object.back) : undefined;
    return message;
  },
};

function createBaseExprRobotConfig(): ExprRobotConfig {
  return {
    mass: undefined,
    inertia: undefined,
    gearing: undefined,
    radius: undefined,
    vmax: undefined,
    tmax: undefined,
    cof: undefined,
    differentialTrackWidth: undefined,
    bumper: undefined,
    frontLeft: undefined,
    frontRight: undefined,
    backLeft: undefined,
    backRight: undefined,
  };
}

export const ExprRobotConfig: MessageFns<ExprRobotConfig> = {
  encode(message: ExprRobotConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mass !== undefined) {
      Expr.encode(message.mass, writer.uint32(10).fork()).join();
    }
    if (message.inertia !== undefined) {
      Expr.encode(message.inertia, writer.uint32(18).fork()).join();
    }
    if (message.gearing !== undefined) {
      Expr.encode(message.gearing, writer.uint32(26).fork()).join();
    }
    if (message.radius !== undefined) {
      Expr.encode(message.radius, writer.uint32(34).fork()).join();
    }
    if (message.vmax !== undefined) {
      Expr.encode(message.vmax, writer.uint32(42).fork()).join();
    }
    if (message.tmax !== undefined) {
      Expr.encode(message.tmax, writer.uint32(50).fork()).join();
    }
    if (message.cof !== undefined) {
      Expr.encode(message.cof, writer.uint32(58).fork()).join();
    }
    if (message.differentialTrackWidth !== undefined) {
      Expr.encode(message.differentialTrackWidth, writer.uint32(66).fork()).join();
    }
    if (message.bumper !== undefined) {
      ExprBumper.encode(message.bumper, writer.uint32(74).fork()).join();
    }
    if (message.frontLeft !== undefined) {
      ExprModule.encode(message.frontLeft, writer.uint32(82).fork()).join();
    }
    if (message.frontRight !== undefined) {
      ExprModule.encode(message.frontRight, writer.uint32(90).fork()).join();
    }
    if (message.backLeft !== undefined) {
      ExprModule.encode(message.backLeft, writer.uint32(98).fork()).join();
    }
    if (message.backRight !== undefined) {
      ExprModule.encode(message.backRight, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprRobotConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprRobotConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mass = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.inertia = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.gearing = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.radius = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.vmax = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.tmax = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.cof = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.differentialTrackWidth = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.bumper = ExprBumper.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.frontLeft = ExprModule.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.frontRight = ExprModule.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.backLeft = ExprModule.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.backRight = ExprModule.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprRobotConfig {
    return {
      mass: isSet(object.mass) ? Expr.fromJSON(object.mass) : undefined,
      inertia: isSet(object.inertia) ? Expr.fromJSON(object.inertia) : undefined,
      gearing: isSet(object.gearing) ? Expr.fromJSON(object.gearing) : undefined,
      radius: isSet(object.radius) ? Expr.fromJSON(object.radius) : undefined,
      vmax: isSet(object.vmax) ? Expr.fromJSON(object.vmax) : undefined,
      tmax: isSet(object.tmax) ? Expr.fromJSON(object.tmax) : undefined,
      cof: isSet(object.cof) ? Expr.fromJSON(object.cof) : undefined,
      differentialTrackWidth: isSet(object.differentialTrackWidth)
        ? Expr.fromJSON(object.differentialTrackWidth)
        : isSet(object.differential_track_width)
        ? Expr.fromJSON(object.differential_track_width)
        : undefined,
      bumper: isSet(object.bumper) ? ExprBumper.fromJSON(object.bumper) : undefined,
      frontLeft: isSet(object.frontLeft)
        ? ExprModule.fromJSON(object.frontLeft)
        : isSet(object.front_left)
        ? ExprModule.fromJSON(object.front_left)
        : undefined,
      frontRight: isSet(object.frontRight)
        ? ExprModule.fromJSON(object.frontRight)
        : isSet(object.front_right)
        ? ExprModule.fromJSON(object.front_right)
        : undefined,
      backLeft: isSet(object.backLeft)
        ? ExprModule.fromJSON(object.backLeft)
        : isSet(object.back_left)
        ? ExprModule.fromJSON(object.back_left)
        : undefined,
      backRight: isSet(object.backRight)
        ? ExprModule.fromJSON(object.backRight)
        : isSet(object.back_right)
        ? ExprModule.fromJSON(object.back_right)
        : undefined,
    };
  },

  toJSON(message: ExprRobotConfig): unknown {
    const obj: any = {};
    if (message.mass !== undefined) {
      obj.mass = Expr.toJSON(message.mass);
    }
    if (message.inertia !== undefined) {
      obj.inertia = Expr.toJSON(message.inertia);
    }
    if (message.gearing !== undefined) {
      obj.gearing = Expr.toJSON(message.gearing);
    }
    if (message.radius !== undefined) {
      obj.radius = Expr.toJSON(message.radius);
    }
    if (message.vmax !== undefined) {
      obj.vmax = Expr.toJSON(message.vmax);
    }
    if (message.tmax !== undefined) {
      obj.tmax = Expr.toJSON(message.tmax);
    }
    if (message.cof !== undefined) {
      obj.cof = Expr.toJSON(message.cof);
    }
    if (message.differentialTrackWidth !== undefined) {
      obj.differentialTrackWidth = Expr.toJSON(message.differentialTrackWidth);
    }
    if (message.bumper !== undefined) {
      obj.bumper = ExprBumper.toJSON(message.bumper);
    }
    if (message.frontLeft !== undefined) {
      obj.frontLeft = ExprModule.toJSON(message.frontLeft);
    }
    if (message.frontRight !== undefined) {
      obj.frontRight = ExprModule.toJSON(message.frontRight);
    }
    if (message.backLeft !== undefined) {
      obj.backLeft = ExprModule.toJSON(message.backLeft);
    }
    if (message.backRight !== undefined) {
      obj.backRight = ExprModule.toJSON(message.backRight);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprRobotConfig>, I>>(base?: I): ExprRobotConfig {
    return ExprRobotConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprRobotConfig>, I>>(object: I): ExprRobotConfig {
    const message = createBaseExprRobotConfig();
    message.mass = (object.mass !== undefined && object.mass !== null) ? Expr.fromPartial(object.mass) : undefined;
    message.inertia = (object.inertia !== undefined && object.inertia !== null)
      ? Expr.fromPartial(object.inertia)
      : undefined;
    message.gearing = (object.gearing !== undefined && object.gearing !== null)
      ? Expr.fromPartial(object.gearing)
      : undefined;
    message.radius = (object.radius !== undefined && object.radius !== null)
      ? Expr.fromPartial(object.radius)
      : undefined;
    message.vmax = (object.vmax !== undefined && object.vmax !== null) ? Expr.fromPartial(object.vmax) : undefined;
    message.tmax = (object.tmax !== undefined && object.tmax !== null) ? Expr.fromPartial(object.tmax) : undefined;
    message.cof = (object.cof !== undefined && object.cof !== null) ? Expr.fromPartial(object.cof) : undefined;
    message.differentialTrackWidth =
      (object.differentialTrackWidth !== undefined && object.differentialTrackWidth !== null)
        ? Expr.fromPartial(object.differentialTrackWidth)
        : undefined;
    message.bumper = (object.bumper !== undefined && object.bumper !== null)
      ? ExprBumper.fromPartial(object.bumper)
      : undefined;
    message.frontLeft = (object.frontLeft !== undefined && object.frontLeft !== null)
      ? ExprModule.fromPartial(object.frontLeft)
      : undefined;
    message.frontRight = (object.frontRight !== undefined && object.frontRight !== null)
      ? ExprModule.fromPartial(object.frontRight)
      : undefined;
    message.backLeft = (object.backLeft !== undefined && object.backLeft !== null)
      ? ExprModule.fromPartial(object.backLeft)
      : undefined;
    message.backRight = (object.backRight !== undefined && object.backRight !== null)
      ? ExprModule.fromPartial(object.backRight)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
