// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DifferentialSample {
    #[prost(double, tag = "1")]
    pub t: f64,
    #[prost(double, tag = "2")]
    pub x: f64,
    #[prost(double, tag = "3")]
    pub y: f64,
    #[prost(double, tag = "4")]
    pub heading: f64,
    #[prost(double, tag = "5")]
    pub vl: f64,
    #[prost(double, tag = "6")]
    pub vr: f64,
    #[prost(double, tag = "7")]
    pub omega: f64,
    #[prost(double, tag = "8")]
    pub al: f64,
    #[prost(double, tag = "9")]
    pub ar: f64,
    #[prost(double, tag = "10")]
    pub alpha: f64,
    #[prost(double, tag = "11")]
    pub fl: f64,
    #[prost(double, tag = "12")]
    pub fr: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ForceVector {
    #[prost(double, tag = "1")]
    pub x: f64,
    #[prost(double, tag = "2")]
    pub y: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SwerveSample {
    #[prost(double, tag = "1")]
    pub t: f64,
    #[prost(double, tag = "2")]
    pub x: f64,
    #[prost(double, tag = "3")]
    pub y: f64,
    #[prost(double, tag = "4")]
    pub heading: f64,
    #[prost(double, tag = "5")]
    pub vx: f64,
    #[prost(double, tag = "6")]
    pub vy: f64,
    #[prost(double, tag = "7")]
    pub omega: f64,
    #[prost(double, tag = "8")]
    pub ax: f64,
    #[prost(double, tag = "9")]
    pub ay: f64,
    #[prost(double, tag = "10")]
    pub alpha: f64,
    #[prost(message, optional, tag = "11")]
    pub fl: ::core::option::Option<ForceVector>,
    #[prost(message, optional, tag = "12")]
    pub fr: ::core::option::Option<ForceVector>,
    #[prost(message, optional, tag = "13")]
    pub bl: ::core::option::Option<ForceVector>,
    #[prost(message, optional, tag = "14")]
    pub br: ::core::option::Option<ForceVector>,
}
include!("entity.serde.rs");
// @@protoc_insertion_point(module)