// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/double.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { DoubleConstraint } from "./constraint/double";
import { DoubleWaypoint } from "./waypoint/double";

export interface DoubleParameters {
  targetDt: number;
  waypoints: DoubleWaypoint[];
  constraints: DoubleConstraint[];
}

function createBaseDoubleParameters(): DoubleParameters {
  return { targetDt: 0, waypoints: [], constraints: [] };
}

export const DoubleParameters: MessageFns<DoubleParameters> = {
  encode(message: DoubleParameters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetDt !== 0) {
      writer.uint32(9).double(message.targetDt);
    }
    for (const v of message.waypoints) {
      DoubleWaypoint.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.constraints) {
      DoubleConstraint.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DoubleParameters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDoubleParameters();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.targetDt = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.waypoints.push(DoubleWaypoint.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.constraints.push(DoubleConstraint.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DoubleParameters {
    return {
      targetDt: isSet(object.targetDt)
        ? globalThis.Number(object.targetDt)
        : isSet(object.target_dt)
        ? globalThis.Number(object.target_dt)
        : 0,
      waypoints: globalThis.Array.isArray(object?.waypoints)
        ? object.waypoints.map((e: any) => DoubleWaypoint.fromJSON(e))
        : [],
      constraints: globalThis.Array.isArray(object?.constraints)
        ? object.constraints.map((e: any) => DoubleConstraint.fromJSON(e))
        : [],
    };
  },

  toJSON(message: DoubleParameters): unknown {
    const obj: any = {};
    if (message.targetDt !== 0) {
      obj.targetDt = message.targetDt;
    }
    if (message.waypoints?.length) {
      obj.waypoints = message.waypoints.map((e) => DoubleWaypoint.toJSON(e));
    }
    if (message.constraints?.length) {
      obj.constraints = message.constraints.map((e) => DoubleConstraint.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DoubleParameters>, I>>(base?: I): DoubleParameters {
    return DoubleParameters.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DoubleParameters>, I>>(object: I): DoubleParameters {
    const message = createBaseDoubleParameters();
    message.targetDt = object.targetDt ?? 0;
    message.waypoints = object.waypoints?.map((e) => DoubleWaypoint.fromPartial(e)) || [];
    message.constraints = object.constraints?.map((e) => DoubleConstraint.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
