// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/expr.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Expr } from "../expression";
import { ExprConstraint } from "./constraint/expr";
import { ExprWaypoint } from "./waypoint/expr";

export interface ExprParameters {
  targetDt: Expr | null;
  waypoints: ExprWaypoint[];
  constraints: ExprConstraint[];
}

function createBaseExprParameters(): ExprParameters {
  return { targetDt: null, waypoints: [], constraints: [] };
}

export const ExprParameters: MessageFns<ExprParameters> = {
  encode(message: ExprParameters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetDt !== undefined && message.targetDt !== null) {
      Expr.encode(message.targetDt, writer.uint32(10).fork()).join();
    }
    for (const v of message.waypoints) {
      ExprWaypoint.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.constraints) {
      ExprConstraint.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprParameters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprParameters();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetDt = Expr.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.waypoints.push(ExprWaypoint.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.constraints.push(ExprConstraint.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprParameters {
    return {
      targetDt: isSet(object.targetDt)
        ? Expr.fromJSON(object.targetDt)
        : isSet(object.target_dt)
        ? Expr.fromJSON(object.target_dt)
        : null,
      waypoints: globalThis.Array.isArray(object?.waypoints)
        ? object.waypoints.map((e: any) => ExprWaypoint.fromJSON(e))
        : [],
      constraints: globalThis.Array.isArray(object?.constraints)
        ? object.constraints.map((e: any) => ExprConstraint.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ExprParameters): unknown {
    const obj: any = {};
    if (message.targetDt !== undefined && message.targetDt !== null) {
      obj.targetDt = Expr.toJSON(message.targetDt);
    }
    if (message.waypoints?.length) {
      obj.waypoints = message.waypoints.map((e) => ExprWaypoint.toJSON(e));
    }
    if (message.constraints?.length) {
      obj.constraints = message.constraints.map((e) => ExprConstraint.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprParameters>, I>>(base?: I): ExprParameters {
    return ExprParameters.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprParameters>, I>>(object: I): ExprParameters {
    const message = createBaseExprParameters();
    message.targetDt = (object.targetDt !== undefined && object.targetDt !== null)
      ? Expr.fromPartial(object.targetDt)
      : null;
    message.waypoints = object.waypoints?.map((e) => ExprWaypoint.fromPartial(e)) || [];
    message.constraints = object.constraints?.map((e) => ExprConstraint.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
