// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/waypoint_id.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface WaypointIDFirst {
}

export interface WaypointIDLast {
}

export interface WaypointIDX {
  idx: number;
}

export interface WaypointID {
  id?: { $case: "first"; first: WaypointIDFirst } | { $case: "last"; last: WaypointIDLast } | {
    $case: "idx";
    idx: WaypointIDX;
  } | undefined;
}

function createBaseWaypointIDFirst(): WaypointIDFirst {
  return {};
}

export const WaypointIDFirst: MessageFns<WaypointIDFirst> = {
  encode(_: WaypointIDFirst, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WaypointIDFirst {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWaypointIDFirst();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): WaypointIDFirst {
    return {};
  },

  toJSON(_: WaypointIDFirst): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<WaypointIDFirst>, I>>(base?: I): WaypointIDFirst {
    return WaypointIDFirst.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WaypointIDFirst>, I>>(_: I): WaypointIDFirst {
    const message = createBaseWaypointIDFirst();
    return message;
  },
};

function createBaseWaypointIDLast(): WaypointIDLast {
  return {};
}

export const WaypointIDLast: MessageFns<WaypointIDLast> = {
  encode(_: WaypointIDLast, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WaypointIDLast {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWaypointIDLast();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): WaypointIDLast {
    return {};
  },

  toJSON(_: WaypointIDLast): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<WaypointIDLast>, I>>(base?: I): WaypointIDLast {
    return WaypointIDLast.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WaypointIDLast>, I>>(_: I): WaypointIDLast {
    const message = createBaseWaypointIDLast();
    return message;
  },
};

function createBaseWaypointIDX(): WaypointIDX {
  return { idx: 0 };
}

export const WaypointIDX: MessageFns<WaypointIDX> = {
  encode(message: WaypointIDX, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.idx !== 0) {
      writer.uint32(8).uint64(message.idx);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WaypointIDX {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWaypointIDX();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.idx = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WaypointIDX {
    return { idx: isSet(object.idx) ? globalThis.Number(object.idx) : 0 };
  },

  toJSON(message: WaypointIDX): unknown {
    const obj: any = {};
    if (message.idx !== 0) {
      obj.idx = Math.round(message.idx);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WaypointIDX>, I>>(base?: I): WaypointIDX {
    return WaypointIDX.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WaypointIDX>, I>>(object: I): WaypointIDX {
    const message = createBaseWaypointIDX();
    message.idx = object.idx ?? 0;
    return message;
  },
};

function createBaseWaypointID(): WaypointID {
  return { id: undefined };
}

export const WaypointID: MessageFns<WaypointID> = {
  encode(message: WaypointID, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.id?.$case) {
      case "first":
        WaypointIDFirst.encode(message.id.first, writer.uint32(10).fork()).join();
        break;
      case "last":
        WaypointIDLast.encode(message.id.last, writer.uint32(18).fork()).join();
        break;
      case "idx":
        WaypointIDX.encode(message.id.idx, writer.uint32(26).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WaypointID {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWaypointID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = { $case: "first", first: WaypointIDFirst.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.id = { $case: "last", last: WaypointIDLast.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.id = { $case: "idx", idx: WaypointIDX.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WaypointID {
    return {
      id: isSet(object.first)
        ? { $case: "first", first: WaypointIDFirst.fromJSON(object.first) }
        : isSet(object.last)
        ? { $case: "last", last: WaypointIDLast.fromJSON(object.last) }
        : isSet(object.idx)
        ? { $case: "idx", idx: WaypointIDX.fromJSON(object.idx) }
        : undefined,
    };
  },

  toJSON(message: WaypointID): unknown {
    const obj: any = {};
    if (message.id?.$case === "first") {
      obj.first = WaypointIDFirst.toJSON(message.id.first);
    } else if (message.id?.$case === "last") {
      obj.last = WaypointIDLast.toJSON(message.id.last);
    } else if (message.id?.$case === "idx") {
      obj.idx = WaypointIDX.toJSON(message.id.idx);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WaypointID>, I>>(base?: I): WaypointID {
    return WaypointID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WaypointID>, I>>(object: I): WaypointID {
    const message = createBaseWaypointID();
    switch (object.id?.$case) {
      case "first": {
        if (object.id?.first !== undefined && object.id?.first !== null) {
          message.id = { $case: "first", first: WaypointIDFirst.fromPartial(object.id.first) };
        }
        break;
      }
      case "last": {
        if (object.id?.last !== undefined && object.id?.last !== null) {
          message.id = { $case: "last", last: WaypointIDLast.fromPartial(object.id.last) };
        }
        break;
      }
      case "idx": {
        if (object.id?.idx !== undefined && object.id?.idx !== null) {
          message.id = { $case: "idx", idx: WaypointIDX.fromPartial(object.id.idx) };
        }
        break;
      }
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
