// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DoubleWaypoint {
    #[prost(double, tag = "1")]
    pub x: f64,
    #[prost(double, tag = "2")]
    pub y: f64,
    #[prost(double, tag = "3")]
    pub heading: f64,
    #[prost(uint64, tag = "4")]
    pub intervals: u64,
    #[prost(bool, tag = "5")]
    pub split: bool,
    #[prost(bool, tag = "6")]
    pub fix_translation: bool,
    #[prost(bool, tag = "7")]
    pub fix_heading: bool,
    #[prost(bool, tag = "8")]
    pub override_intervals: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprWaypoint {
    #[prost(message, optional, tag = "1")]
    pub x: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "2")]
    pub y: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "3")]
    pub heading: ::core::option::Option<super::Expr>,
    #[prost(uint64, tag = "4")]
    pub intervals: u64,
    #[prost(bool, tag = "5")]
    pub split: bool,
    #[prost(bool, tag = "6")]
    pub fix_translation: bool,
    #[prost(bool, tag = "7")]
    pub fix_heading: bool,
    #[prost(bool, tag = "8")]
    pub override_intervals: bool,
}
include!("entity.parameters.waypoint.serde.rs");
// @@protoc_insertion_point(module)