// @generated
// This file is @generated by prost-build.
#[derive(::required_proc::Required)]
#[required(prefix="Required")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DoubleMaxAcceleration {
    #[prost(double, tag = "1")]
    pub max: f64,
}
#[derive(::required_proc::Required)]
#[required(prefix="Required")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprMaxAcceleration {
    #[prost(message, optional, tag = "1")]
    pub max: ::core::option::Option<super::super::Expr>,
}
include!("entity.parameters.constraint.max_acceleration.serde.rs");
// @@protoc_insertion_point(module)