// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/constraint/expr.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { WaypointID } from "../waypoint_id";
import { ExprMaxAcceleration } from "./max_acceleration/expr";
import { ExprMaxVelocity } from "./maxvelocity/expr";

export interface ExprConstraint {
  enabled: boolean;
  from: WaypointID | null;
  to:
    | WaypointID
    | null;
  /**
   * ExprMaxVelocity maxvelocity = 4;
   * ExprMaxAcceleration max_acceleration = 5;
   */
  data?:
    | { $case: "maxVelocity"; value: ExprMaxVelocity }
    | { $case: "maxAcceleration"; value: ExprMaxAcceleration }
    | null;
}

function createBaseExprConstraint(): ExprConstraint {
  return { enabled: false, from: null, to: null, data: null };
}

export const ExprConstraint: MessageFns<ExprConstraint> = {
  encode(message: ExprConstraint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.from !== undefined && message.from !== null) {
      WaypointID.encode(message.from, writer.uint32(18).fork()).join();
    }
    if (message.to !== undefined && message.to !== null) {
      WaypointID.encode(message.to, writer.uint32(26).fork()).join();
    }
    switch (message.data?.$case) {
      case "maxVelocity":
        ExprMaxVelocity.encode(message.data.value, writer.uint32(34).fork()).join();
        break;
      case "maxAcceleration":
        ExprMaxAcceleration.encode(message.data.value, writer.uint32(42).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprConstraint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprConstraint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.from = WaypointID.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.to = WaypointID.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = { $case: "maxVelocity", value: ExprMaxVelocity.decode(reader, reader.uint32()) };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.data = { $case: "maxAcceleration", value: ExprMaxAcceleration.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprConstraint {
    return {
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      from: isSet(object.from) ? WaypointID.fromJSON(object.from) : null,
      to: isSet(object.to) ? WaypointID.fromJSON(object.to) : null,
      data: isSet(object.maxVelocity)
        ? { $case: "maxVelocity", value: ExprMaxVelocity.fromJSON(object.maxVelocity) }
        : isSet(object.max_velocity)
        ? { $case: "maxVelocity", value: ExprMaxVelocity.fromJSON(object.max_velocity) }
        : isSet(object.maxAcceleration)
        ? { $case: "maxAcceleration", value: ExprMaxAcceleration.fromJSON(object.maxAcceleration) }
        : isSet(object.max_acceleration)
        ? { $case: "maxAcceleration", value: ExprMaxAcceleration.fromJSON(object.max_acceleration) }
        : null,
    };
  },

  toJSON(message: ExprConstraint): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.from !== undefined && message.from !== null) {
      obj.from = WaypointID.toJSON(message.from);
    }
    if (message.to !== undefined && message.to !== null) {
      obj.to = WaypointID.toJSON(message.to);
    }
    if (message.data?.$case === "maxVelocity") {
      obj.maxVelocity = ExprMaxVelocity.toJSON(message.data.value);
    } else if (message.data?.$case === "maxAcceleration") {
      obj.maxAcceleration = ExprMaxAcceleration.toJSON(message.data.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprConstraint>, I>>(base?: I): ExprConstraint {
    return ExprConstraint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprConstraint>, I>>(object: I): ExprConstraint {
    const message = createBaseExprConstraint();
    message.enabled = object.enabled ?? false;
    message.from = (object.from !== undefined && object.from !== null) ? WaypointID.fromPartial(object.from) : null;
    message.to = (object.to !== undefined && object.to !== null) ? WaypointID.fromPartial(object.to) : null;
    switch (object.data?.$case) {
      case "maxVelocity": {
        if (object.data?.value !== undefined && object.data?.value !== null) {
          message.data = { $case: "maxVelocity", value: ExprMaxVelocity.fromPartial(object.data.value) };
        }
        break;
      }
      case "maxAcceleration": {
        if (object.data?.value !== undefined && object.data?.value !== null) {
          message.data = { $case: "maxAcceleration", value: ExprMaxAcceleration.fromPartial(object.data.value) };
        }
        break;
      }
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
