// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: entity/parameters/constraint/maxvelocity/expr.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Expr } from "../../../expression";

export interface ExprMaxVelocity {
  max: Expr | undefined;
}

export interface TestExpr {
  test: string;
}

function createBaseExprMaxVelocity(): ExprMaxVelocity {
  return { max: undefined };
}

export const ExprMaxVelocity: MessageFns<ExprMaxVelocity> = {
  encode(message: ExprMaxVelocity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.max !== undefined) {
      Expr.encode(message.max, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExprMaxVelocity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExprMaxVelocity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.max = Expr.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExprMaxVelocity {
    return { max: isSet(object.max) ? Expr.fromJSON(object.max) : undefined };
  },

  toJSON(message: ExprMaxVelocity): unknown {
    const obj: any = {};
    if (message.max !== undefined) {
      obj.max = Expr.toJSON(message.max);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExprMaxVelocity>, I>>(base?: I): ExprMaxVelocity {
    return ExprMaxVelocity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExprMaxVelocity>, I>>(object: I): ExprMaxVelocity {
    const message = createBaseExprMaxVelocity();
    message.max = (object.max !== undefined && object.max !== null) ? Expr.fromPartial(object.max) : undefined;
    return message;
  },
};

function createBaseTestExpr(): TestExpr {
  return { test: "" };
}

export const TestExpr: MessageFns<TestExpr> = {
  encode(message: TestExpr, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.test !== "") {
      writer.uint32(10).string(message.test);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TestExpr {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTestExpr();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.test = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TestExpr {
    return { test: isSet(object.test) ? globalThis.String(object.test) : "" };
  },

  toJSON(message: TestExpr): unknown {
    const obj: any = {};
    if (message.test !== "") {
      obj.test = message.test;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TestExpr>, I>>(base?: I): TestExpr {
    return TestExpr.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TestExpr>, I>>(object: I): TestExpr {
    const message = createBaseTestExpr();
    message.test = object.test ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
