// @generated
// This file is @generated by prost-build.
#[derive(::required_proc::Required)]
#[required(prefix="Required")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DoubleModule {
    #[prost(double, tag = "1")]
    pub x: f64,
    #[prost(double, tag = "2")]
    pub y: f64,
}
#[derive(::required_proc::Required)]
#[required(prefix="Required")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DoubleBumper {
    #[prost(double, tag = "1")]
    pub front: f64,
    #[prost(double, tag = "2")]
    pub left: f64,
    #[prost(double, tag = "3")]
    pub right: f64,
    #[prost(double, tag = "4")]
    pub back: f64,
}
#[derive(::required_proc::Required)]
#[required(prefix="Required")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DoubleRobotConfig {
    #[prost(double, tag = "1")]
    pub mass: f64,
    #[prost(double, tag = "2")]
    pub inertia: f64,
    #[prost(double, tag = "3")]
    pub gearing: f64,
    #[prost(double, tag = "4")]
    pub radius: f64,
    #[prost(double, tag = "5")]
    pub vmax: f64,
    #[prost(double, tag = "6")]
    pub tmax: f64,
    #[prost(double, tag = "7")]
    pub cof: f64,
    #[prost(double, tag = "8")]
    pub differential_track_width: f64,
    /// double bumper_front = 9;
    /// double bumper_left = 10;
    /// double bumper_back = 11;
    /// double bumper_right = 12;
    /// double fl_x = 13;
    /// double fl_y = 14;
    /// double fr_x = 15;
    /// double fl_
    #[prost(message, optional, tag = "9")]
    pub bumper: ::core::option::Option<DoubleBumper>,
    #[prost(message, optional, tag = "10")]
    pub front_left: ::core::option::Option<DoubleModule>,
    #[prost(message, optional, tag = "11")]
    pub front_right: ::core::option::Option<DoubleModule>,
    #[prost(message, optional, tag = "12")]
    pub back_left: ::core::option::Option<DoubleModule>,
    #[prost(message, optional, tag = "13")]
    pub back_right: ::core::option::Option<DoubleModule>,
}
#[derive(::required_proc::Required)]
#[required(prefix="Required")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprModule {
    #[prost(message, optional, tag = "1")]
    pub x: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "2")]
    pub y: ::core::option::Option<super::Expr>,
}
#[derive(::required_proc::Required)]
#[required(prefix="Required")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprBumper {
    #[prost(message, optional, tag = "1")]
    pub front: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "2")]
    pub left: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "3")]
    pub right: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "4")]
    pub back: ::core::option::Option<super::Expr>,
}
#[derive(::required_proc::Required)]
#[required(prefix="Required")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprRobotConfig {
    #[prost(message, optional, tag = "1")]
    pub mass: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "2")]
    pub inertia: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "3")]
    pub gearing: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "4")]
    pub radius: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "5")]
    pub vmax: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "6")]
    pub tmax: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "7")]
    pub cof: ::core::option::Option<super::Expr>,
    #[prost(message, optional, tag = "8")]
    pub differential_track_width: ::core::option::Option<super::Expr>,
    /// Expr bumper_front = 9;
    /// Expr bumper_left = 10;
    /// Expr bumper_back = 11;
    /// Expr bumper_right = 12;
    /// Expr fl_x = 13;
    /// Expr fl_y = 14;
    /// Expr fr_x = 15;
    /// Expr fl_
    #[prost(message, optional, tag = "9")]
    pub bumper: ::core::option::Option<ExprBumper>,
    #[prost(message, optional, tag = "10")]
    pub front_left: ::core::option::Option<ExprModule>,
    #[prost(message, optional, tag = "11")]
    pub front_right: ::core::option::Option<ExprModule>,
    #[prost(message, optional, tag = "12")]
    pub back_left: ::core::option::Option<ExprModule>,
    #[prost(message, optional, tag = "13")]
    pub back_right: ::core::option::Option<ExprModule>,
}
include!("entity.parameters.robotconfig.serde.rs");
// @@protoc_insertion_point(module)