// @generated
// This file is @generated by prost-build.
#[required_proc::make_required]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EchoSwerveSampleRequest {
    #[prost(message, optional, tag = "1")]
    pub sample: ::core::option::Option<super::super::entity::SwerveSample>,
}
#[required_proc::make_required]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EchoSwerveSampleResponse {
    #[prost(message, optional, tag = "1")]
    pub sample: ::core::option::Option<super::super::entity::SwerveSample>,
}
#[required_proc::make_required]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenerateRequest {
    #[prost(message, optional, tag = "1")]
    pub trajectory: ::core::option::Option<super::super::entity::TrajectoryFile>,
}
#[required_proc::make_required]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenerateResponse {
    #[prost(message, optional, tag = "1")]
    pub trajectory: ::core::option::Option<super::super::entity::TrajectoryFile>,
}
#[required_proc::make_required]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDefaultTrajectoryResponse {
    #[prost(message, optional, tag = "1")]
    pub trajectory: ::core::option::Option<super::super::entity::TrajectoryFile>,
}
include!("service.commands.serde.rs");
// @@protoc_insertion_point(module)