// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EchoSwerveSampleRequest {
    #[prost(message, optional, tag = "1")]
    pub sample: ::core::option::Option<super::super::entity::SwerveSample>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EchoSwerveSampleResponse {
    #[prost(message, optional, tag = "1")]
    pub sample: ::core::option::Option<super::super::entity::SwerveSample>,
}
include!("service.commands.serde.rs");
// @@protoc_insertion_point(module)