// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DoubleMaxVelocity {
    #[prost(double, tag = "1")]
    pub max: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestDouble {
    #[prost(string, tag = "1")]
    pub test: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExprMaxVelocity {
    #[prost(message, optional, tag = "1")]
    pub max: ::core::option::Option<super::super::Expr>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestExpr {
    #[prost(string, tag = "1")]
    pub test: ::prost::alloc::string::String,
}
include!("entity.parameters.constraint.maxvelocity.serde.rs");
// @@protoc_insertion_point(module)